antora:
  extensions:
  - '@opendevise/antora-release-line-extension'
  - require: '@springio/antora-extensions'
    root_component_name: 'ldap'
site:
  title: Spring LDAP
  url: https://docs.spring.io/spring-ldap/reference
  robots: allow
git:
  ensure_git_suffix: false
content:
  sources:
  - url: https://github.com/spring-projects/spring-ldap
    # Refname matching:
    # https://docs.antora.org/antora/latest/playbook/content-refname-matching/
    branches: [main,'({3..9}).+({0..9}).x', '!(3.0.x)']
    tags: ['({3..9}).+({0..9}).+({0..9})?(-{RC,M}+({0..9}))', '!(3.0.+({0..9})?(-{RC,M}+({0..9})))', '!(3.1.+({0..4})?(-{RC,M}+({0..9})))']
asciidoc:
  extensions:
    - '@asciidoctor/tabs'
    - '@springio/asciidoctor-extensions'
    - '@springio/asciidoctor-extensions/include-code-extension'
  attributes:
    page-related-doc-categories: security
    page-related-doc-projects: framework
    page-pagination: ''
    hide-uri-scheme: '@'
    tabs-sync-option: '@'
urls:
  latest_version_segment_strategy: redirect:to
  latest_version_segment: ''
  redirect_facility: httpd
runtime:
  log:
    failure_level: warn
ui:
  bundle:
    url: https://github.com/spring-io/antora-ui-spring/releases/download/v0.4.3/ui-bundle.zip
    snapshot: true
